### ISSUE TITLE
[ClassCastException: java.lang.String cannot be cast to scala.Function0]

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap#49]
I use the latest snapshot (1.0-P24-SNAPSHOT) with BS3.

I have a form field named "zip" (part of an address).
When I write
```
@b3.text(myForm("zip"), ...)
```
I get:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ClassCastException: java.lang.String cannot be cast to scala.Function0]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:169) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:131) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.core.j.JavaHttpErrorHandlerAdapter$$anonfun$onServerError$1.apply(JavaHttpErrorHandlerAdapter.scala:22) [play_2.11-2.4.6.jar:2.4.6]
	at play.core.j.JavaHttpErrorHandlerAdapter$$anonfun$onServerError$1.apply(JavaHttpErrorHandlerAdapter.scala:22) [play_2.11-2.4.6.jar:2.4.6]
	at play.core.j.JavaHelpers$$anonfun$invokeWithContext$1.apply(JavaHelpers.scala:140) [play_2.11-2.4.6.jar:2.4.6]
	at play.core.j.JavaHelpers$$anonfun$invokeWithContext$1.apply(JavaHelpers.scala:139) [play_2.11-2.4.6.jar:2.4.6]
	at play.core.j.JavaHelpers$class.withContext(JavaHelpers.scala:151) [play_2.11-2.4.6.jar:2.4.6]
	at play.core.j.JavaHelpers$.withContext(JavaHelpers.scala:160) [play_2.11-2.4.6.jar:2.4.6]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to scala.Function0
	at views.html.bs.package$BSFieldInfo$$anonfun$constraintsArgs$1.apply(package.scala:149) ~[play-bootstrap-core_2.11.jar:1.0-P24-SNAPSHOT]
	at views.html.bs.package$BSFieldInfo$$anonfun$constraintsArgs$1.apply(package.scala:143) ~[play-bootstrap-core_2.11.jar:1.0-P24-SNAPSHOT]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.7.jar:na]
	at views.html.bs.package$BSFieldInfo$.constraintsArgs(package.scala:143) ~[play-bootstrap-core_2.11.jar:1.0-P24-SNAPSHOT]
	at views.html.bs.package$BSFieldInfo.innerArgsMap$lzycompute(package.scala:89) ~[play-bootstrap-core_2.11.jar:1.0-P24-SNAPSHOT]
```

When I change it to "zip1" or something differnt it works.

**Comment by mkurz** [comment]
I am not sure if it is my fault because I use my own Data Binders.

**Comment by adrianhurt** [comment]
Hi @mkurz, could you try using `@helper.inputText(myForm("zip"), ...)` instead? This will tell us if it's a problem of the library or not.

**Comment by mkurz** [comment]
`@helper.inputText(myForm("zip"))` works.
`@b3.text(myForm("zip"))` does not work.
Problem is your library.

**Comment by mkurz** [comment]
This is the declaration of the field in the form:
```java
	@Required @NonEmpty
	@Pattern(value="[1-9][0-9]{3}", message="error.zip")
	private String zip;
	// also field has getter and setter
```

**Comment by mkurz** [comment]
I am using Java not Scala.

**Comment by mkurz** [comment]
This is probably because of the HTML 5 constraint stuff you have been adding with the last commits.

**Comment by adrianhurt** [comment]
Ok, I see, you're right. It seems it doesn't happen in Scala, but it does with Java using the pattern constraint. Thank you for finding the bug. I'll try to find out what's happening and fix it as soon as possible.

**Comment by mkurz** [comment]
Thanks!

**Comment by adrianhurt** [comment]
Hi, it's fixed now. I didn't know that Java and Scala versions give a different type result for the pattern constraint.

**Comment by mkurz** [comment]
Thanks! I will try on Monday.

**Comment by mkurz** [comment]
Thanks @adrianhurt! I works now.
Thank you for you fast reponses and for your first class support for this library :+1:
