### ISSUE TITLE
Compilation error: not found: value b3

### ISSUE THREAD

**Issue by sallareznov** [adrianhurt/play-bootstrap#60]
Hi,
I just started to use your library but I'm having a compilation problem. I use `Play Framework` in its 2.5 version, and I added the `play-bootstrap` dependency in my `build.sbt` file :

```scala
"com.adrianhurt" %% "play-bootstrap" % "1.0-P25-B3"
```

Here is what I have in my template:

```scala
@import models.FareData
@import b3.vertical.fieldConstructor
@(fareForm: Form[FareData])(implicit messages: Messages)

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="@routes.Assets.at("stylesheets/index.css")">
    </head>
    <body>
        <div id="container">
            @b3.form(routes.WebsiteController.computeFarePrice()) {
                @b3.email( fareForm("email"), '_label -> "Email", 'placeholder -> "example@mail.com" )
                @b3.password( fareForm("password"), '_label -> "Password", 'placeholder -> "Password" )
                @b3.checkbox( fareForm("remember"), '_text -> "Remember me", 'value -> true )
                @b3.submit('class -> "btn btn-default"){ Sign in }
            }
        </div>
    </body>
</html>
```

When I compile my sources, Play tells me that I can't use b3 helpers (`Compilation error[not found: value b3]`)

```sh
play.sbt.PlayExceptions$CompilationException: Compilation error[not found: value b3]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
```

**Comment by adrianhurt** [comment]
It's strange. Have you tried to clean the project, exit and run it again?

**Comment by sallareznov** [comment]
Oh, it works. I restarted my server and that did the trick. Thanks for the library and for your fast feedback. :)

**Comment by sallareznov** [comment]
My problem is solved. I'm closing the issue.

**Comment by adrianhurt** [comment]
You're welcome!

**Comment by anubhav100** [comment]
having same problem help please

**Comment by adrianhurt** [comment]
Hi, if your project doesn't find the `b3 value` is probably due to an installation problem. To install the plugin you only need to add this to `build.sbt`:
```
libraryDependencies ++= Seq(
  "com.adrianhurt" %% "play-bootstrap" % "1.0-P25-B3"
)
```
where you can change `1.0-P25-B3` for your corresponding version of Play and Bootstrap.

Then, execute `clean` inside `activator` and exit, and finally run activator again and try it.
