### ISSUE TITLE
play-bootstrap3_2.11 causes NoSuchMethodException on run 

### ISSUE THREAD

**Issue by vitalijzad** [adrianhurt/play-bootstrap#62]
This dependency:

`"com.adrianhurt" % "play-bootstrap3_2.11" % "0.4.5-P24"`

When I run activator, causes this exception:

```
java.lang.NoSuchMethodException: play.core.server.NettyServer.mainDevHttpMode(play.core.BuildLink, play.core.BuildDocHandler, int)
        at java.lang.Class.getMethod(Class.java:1773)
        at play.PlayRun$class.play$PlayRun$$startDevMode(PlayRun.scala:318)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:103)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:103)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:125)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:96)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

With `scalaVersion := "2.11.1"` and `sbt launcher version 0.13.5`.

When the dependecy is removed, the project runs.

The bug can be reproduced by running the following project: https://github.com/JUGItalia/JUG_Events

**Comment by vitalijzad** [comment]
Sorry, the correct version for Play 2.3 is 0.4.5-P23
