### ISSUE TITLE
java.lang.NullPointerException when using args in the controls

### ISSUE THREAD

**Issue by LeonorLunatech** [adrianhurt/play-bootstrap#85]
I am implementing a project using the following form:
```
@import b3.vertical.fieldConstructor
@import models.User
@import viewModels.DishForm

@(admin: User, dishForm: Form[DishForm])(implicit messages: play.api.i18n.Messages)
@main("New dish", admin, isUserAdmin = true) {
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a data-toggle="tab" href="#newDish">Create new</a></li>
        <li role="presentation" ><a href="@controllers.routes.DishController.getAllDishes">All dishes</a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="newDish">
            <br>
            @b3.form(controllers.routes.DishController.createNewDish) {
                <div class="row">
                    <div class="col col-lg-6">
                        @b3.text( dishForm("name"), '_label -> "Name", 'placeholder -> "Short dish name" )
                        @b3.textarea( dishForm("description"), '_label -> "Description",  'placeholder -> "Dish description", 'rows -> 4)
                        @b3.text( dishForm("remarks"), '_label -> "Additional remarks", 'placeholder -> "Optional" )
                        <br>
                        @b3.submit('class -> "btn btn-primary"){ Create dish }
                    </div>
                </div>
            }

        </div>
    </div>
}
```
Everything was working OK, until I implemented unit test for the controller.
I get the following error :
```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at views.html.bs.Args$.msg(Args.scala:70)
	at views.html.bs.package$BSFieldInfo$$anonfun$innerArgsMap$2.apply(package.scala:76)
	at views.html.bs.package$BSFieldInfo$$anonfun$innerArgsMap$2.apply(package.scala:76)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at views.html.bs.package$BSFieldInfo.innerArgsMap$lzycompute(package.scala:76)
	at views.html.bs.package$BSFieldInfo.innerArgsMap(package.scala:72)
	at views.html.b3.inputWrapped_Scope0$inputWrapped$$anonfun$apply$1.apply(inputWrapped.template.scala:28)
	at views.html.b3.inputWrapped_Scope0$inputWrapped$$anonfun$apply$1.apply(inputWrapped.template.scala:26)
	at views.html.bs.package$.inputFormField(package.scala:212)
	at views.html.b3.package$.inputFormGroup(package.scala:161)
	at views.html.b3.inputWrapped_Scope0$inputWrapped.apply(inputWrapped.template.scala:34)
	at views.html.b3.package$.inputType(package.scala:179)
	at views.html.b3.package$.text(package.scala:181)
	at views.html.admin.newDish_Scope0$newDish_Scope1$newDish$$anonfun$apply$1.apply(newDish.template.scala:43)
	at views.html.admin.newDish_Scope0$newDish_Scope1$newDish$$anonfun$apply$1.apply(newDish.template.scala:40)
	at views.html.b3.form_Scope0$form.apply(form.template.scala:27)
	at views.html.admin.newDish_Scope0$newDish_Scope1$newDish.apply(newDish.template.scala:40)
	at controllers.DishController$$anonfun$getNewDish$1$$anonfun$apply$5$$anonfun$apply$6.apply(DishController.scala:40)
	at controllers.DishController$$anonfun$getNewDish$1$$anonfun$apply$5$$anonfun$apply$6.apply(DishController.scala:38)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The funny part is that the error disappears if I remove the args from the controllers, like this:

```
@import b3.vertical.fieldConstructor
@import models.User
@import viewModels.DishForm

@(admin: User, dishForm: Form[DishForm])(implicit messages: play.api.i18n.Messages)
@main("New dish", admin, isUserAdmin = true) {
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a data-toggle="tab" href="#newDish">Create new</a></li>
        <li role="presentation" ><a href="@controllers.routes.DishController.getAllDishes">All dishes</a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="newDish">
            <br>
            @b3.form(controllers.routes.DishController.createNewDish) {
                <div class="row">
                    <div class="col col-lg-6">
                        @b3.text( dishForm("name"))
                        @b3.textarea( dishForm("description"))
                        @b3.text( dishForm("remarks"))
                        <br>
                        @b3.submit('class -> "btn btn-primary"){ Create dish }
                    </div>
                </div>
            }
        </div>
    </div>
}
```
What I'm I missing here?

**Comment by adrianhurt** [comment]
I'm sooo sorry. I totally forgot this issue. Could you solve it?

**Comment by LeonorLunatech** [comment]
No, I did not solve it :(

**Comment by mkurz** [comment]
@LeonorLunatech Which version of Play and play-bootstrap are you using?
Can you provide a simple project which reproduces the problem?
I think this has something todo with i18n messages.

**Comment by adrianhurt** [comment]
Yes, please @LeonorLunatech, give us more clues. We need at least the version of Play and play-bootstrap you are using and the code for the unit test that throws the exception. But even better would be a simple project with the problem as @mkurz said.

**Comment by mkurz** [comment]
Ping @LeonorLunatech

**Comment by LeonorLunatech** [comment]
Sorry for not replying. I'm not actively working in that project anymore. But tomorrow I'll have some time to look into it. I'll come back to you :)

**Comment by mkurz** [comment]
@LeonorLunatech Thanks!

**Comment by LeonorLunatech** [comment]
[test.zip](https://github.com/adrianhurt/play-bootstrap/files/1097992/test.zip)

I have created a very simple project that reproduces the issue.
So the problem is in integration test. Just hit `sbt test` to see the error occurring

**Comment by mkurz** [comment]
@LeonorLunatech I won't have time til beginning of July to check this. But thanks for the test project.

@adrianhurt Maybe you can check?

**Comment by adrianhurt** [comment]
Sorry for the delay, @LeonorLunatech! I've just checked your test. I don't know enough about tests with Mockito, but it seems it's not a problem with __play-bootstrap__. The test creates a `Messages` instance with __null__ value. I just simply added this line to `DishController.getNewDish`:

```
println(implicitly[Messages])
```

And it prints null at the console. In fact, you can add this other line before `b3.form` within `newDish.scala.html` and you will get another __null exception__
```
@Messages("hello")
```

So check the documentation of Mockito or find more examples about how to test a view.

**Comment by mkurz** [comment]
I think this can be closed as it seems it has nothing to do with play-bootstrap but the messages are missing in the tests.
